spring.application.name=ESMSProject1

spring.datasource.url=jdbc:mysql://localhost:3306/ESMSProjectdb
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.mail.username=youremail@gmail.com
spring.mail.password=your_password